# Generated by Django 4.2.13 on 2024-07-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageproduct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='url_slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
