# Generated by Django 4.2.13 on 2024-07-25 19:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageproduct', '0004_products_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_description',
            field=ckeditor.fields.RichTextField(default='Embrace effortless style and supreme comfort with our Classic Oversized T-Shirt. Designed for those who value both fashion and relaxation, this t-shirt features a generous, relaxed fit that drapes elegantly over the body, offering a laid-back yet stylish silhouette.'),
            preserve_default=False,
        ),
    ]
