# Generated by Django 4.2.13 on 2024-07-30 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageproduct', '0005_alter_products_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVarient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=5, null=True)),
                ('varient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varient', to='manageproduct.products')),
            ],
        ),
    ]
