# Generated by Django 4.2.13 on 2024-07-30 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageproduct', '0006_productvarient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvarient',
            old_name='varient',
            new_name='product',
        ),
    ]
