# Generated by Django 4.2.13 on 2024-07-20 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageproduct', '0004_products_discount'),
        ('manageorders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_id', to='manageproduct.products'),
            preserve_default=False,
        ),
    ]
