# Generated by Django 4.2.13 on 2024-07-21 06:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manageproduct', '0004_products_discount'),
        ('manageorders', '0003_alter_orders_delivery_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='product_id',
        ),
        migrations.AddField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_status',
            field=models.CharField(choices=[('Not Paid', 'Not Paid'), ('Paid', 'Paid')], default='Not Paid', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='manageorders.orders')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='manageproduct.products')),
            ],
        ),
    ]
