# Generated by Django 4.2.13 on 2024-07-21 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageproduct', '0004_products_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manageorders', '0004_remove_orders_product_id_orders_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='manageorders.orders'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='manageproduct.products'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
