# Generated by Django 4.2.13 on 2024-07-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageorders', '0005_alter_orderitems_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='name',
            field=models.CharField(blank=True, default='Order items for', max_length=10, null=True),
        ),
    ]
