# Generated by Django 4.2.13 on 2024-07-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageorders', '0006_orderitems_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
