# Generated by Django 4.2.13 on 2024-07-31 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageorders', '0007_orderitems_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='size',
            field=models.TextField(default='S'),
            preserve_default=False,
        ),
    ]
